Repository accordproject/techdocs, pull requests merged in 2019-10, with the labels that each got.

#103 fix(docs): grammar changes
  docs/accordproject-installation.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#104 doc(0.20) WIP some initial structure for new documentation
  docs/0.13to0.20.md
  docs/markup-cicero.md
  docs/markup-commonmark.md
  docs/markup-expr.md
  docs/markup-variables-blocks.md
  docs/model-concerto.md
  docs/ref-markup.md
  website/i18n/en.json
  website/sidebars.json
Labels: 0.20-alpha, Type: Release 📅

#107 fix(*): correct typos
  docs/accordproject-resources.md
  docs/cicero-api.md
  docs/ergo-cli.md
  docs/logic-ergo.md
  docs/logic-simple-expr.md
  docs/logic-stmt.md
  docs/ref-logic-specification.md
  docs/ref-markup.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#102 fix(styles): fix wrong opacity on hovering
  website/static/css/main.css
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#117 Fix spacing issues in sidebar nav menu
  website/static/css/main.css
Labels: Difficulty: Starter, Good First Issue (Taken), Hacktoberfest, Type: Bug 🐛

#122 fix(main page): fix url in slack button - I121
  website/core/Footer.js
  website/pages/en/index.js
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#135 Updated alt text for images on the home page
  website/pages/en/index.js
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest

#139 docs(README): add license badge - I82
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#140 fix(docs): correct a typo
  docs/accordproject.md
Labels: Difficulty: Starter, Hacktoberfest

#143 fix(docs): change for better readability
  docs/example-eatapple.md
Labels: Difficulty: Starter, Hacktoberfest

#120 fix(*): multiple typos
  CONTRIBUTING.md
  docs/advanced-latedelivery.md
  docs/ergo-tutorial.md
  docs/logic-simple-expr.md
  docs/ref-logic.md
  docs/ref-testing.md
  docs/spec-packaging.md
  website/versioned_docs/version-0.12.0/accordproject-resources.md
  website/versioned_docs/version-0.12.0/ergo-tutorial.md
  website/versioned_docs/version-0.12.0/logic-simple-expr.md
  website/versioned_docs/version-0.12.0/logic-stmt.md
  website/versioned_docs/version-0.12.0/ref-logic.md
  website/versioned_docs/version-0.12.0/ref-testing.md
  website/versioned_docs/version-0.12.0/spec-packaging.md
  website/versioned_docs/version-0.12.3/advanced-latedelivery.md
  website/versioned_docs/version-0.12.3/spec-packaging.md
  website/versioned_docs/version-0.13.0/ergo-cli.md
  website/versioned_docs/version-0.13.0/logic-stmt.md
  website/versioned_docs/version-0.13.0/spec-packaging.md
Labels: Difficulty: Starter, Hacktoberfest

#124 fix(docs): replace links to concerto from Hyperledger to Accord repo
  docs/accordproject.md
  docs/basic-templates.md
  docs/example-eatapple.md
  docs/logic-complex-type.md
  docs/logic-ergo.md
  docs/spec-packaging.md
  docs/spec-template.md
  website/pages/en/index.js
Labels: Category: Concerto, Difficulty: Starter, Hacktoberfest

#147 Writing markup-commonmark.md
  docs/markup-commonmark.md
Labels: 0.20-alpha

#150 fix(docs): correct typo mistakes
  docs/advanced-latedelivery.md
Labels: Difficulty: Starter, Hacktoberfest

#158 fix(website): change header logo to avoid search bar overlapping in smaller resolution
  website/static/css/main.css
  website/static/img/Accord-Project-logo-small.svg
Labels: A11Y 🔓, Difficulty: Starter, Good First Issue :octocat:, Hacktoberfest, Type: Bug 🐛

#166 fix(DEVELOPERS): add website navigation step - I156
  DEVELOPERS.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#175 fixed formatting for markup-commonmark.md
  docs/markup-commonmark.md
Labels: 0.20-alpha, Category: Cicero, Difficulty: Starter, Hacktoberfest

#182 fix(CONTRIBUTING): broken coc link - I181
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest

#183 fix(docs): correct json for cicero draft - I87
  docs/markup-variables-blocks.md
Labels: 0.20-alpha, Category: Cicero

#131 feat(docs): add ecosystem table - I80
  README.md
Labels: Difficulty: Medium, Hacktoberfest

#162 docs: seed allcontributor data
  .all-contributorsrc
  README.md
  scripts/seed_contributors.sh
Labels: Difficulty: Medium, Hacktoberfest, Type: Feature Request 🛍️

#196 docs(*): update markdown files and fix typos - I257
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#195 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#204 fix(docs): correct link - I203
  docs/tutorial-nodejs.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Bug 🐛

#202 Updated the LF url
  website/core/Footer.js
Labels: Difficulty: Starter, Hacktoberfest

#208 fix(readme): fix broken link in ecosystem
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#191 fix(website): add alt texts to images - I113
  website/core/Footer.js
  website/pages/en/index.js
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest

#225 fix(README): closing tag on ecosystem
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#224 style(css): increased spacing for navbar
  website/static/css/main.css
Labels: Difficulty: Starter, Hacktoberfest

#232 Added style hyperlinks
  website/static/css/main.css
Labels: A11Y 🔓, Difficulty: Starter, Good First Issue :octocat:, Hacktoberfest, Type: Bug 🐛

#238 fix(README): typo - I237
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#234 Code text with higher contrast
  website/static/css/main.css
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest

#241 refactor(references): Move migration guides to reference section
  docs/migrate-0.13-0.20.md
  website/i18n/en.json
  website/sidebars.json
Labels: 0.20

#235 docs(reference): operator precedence (ergo#35)
  docs/ref-logic.md
Labels: Category: Ergo, Difficulty: Starter, Hacktoberfest
