Repository accordproject/techdocs, pull requests merged in 2020-06, with the labels that each got.

#291 docs(concerto-cli):change directory name from "models" to "model"
  website/versioned_docs/version-0.20/concerto-cli.md
Labels: Category: Models, Type: Bug 🐛

#294 feat(assets): update ap stack flow diagram
  assets/APFlow.png
  assets/APStack.png
Labels: 0.21, dependencies

#295 feat(assets): update ap stack flow diagram error
  assets/APStack.png
Labels: Type: Bug 🐛
